apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "order.fullname" . }}
  labels:
    {{- include "order.labels" . | nindent 4 }}
spec:
  host: {{ include "order.fullname" . }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 1000
    outlierDetection:
      # 连续 5 次 5xx → 驱逐实例
      consecutive5xxErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 50
