apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order.fullname" . }}-secret
  labels:
    {{- include "order.labels" . | nindent 4 }}
type: Opaque
stringData:
  # 数据库密码
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secret.datasource.password | quote }}
  # Kafka SASL 认证（SCRAM-SHA-256）
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: >-
    org.apache.kafka.common.security.scram.ScramLoginModule required
    username={{ .Values.secret.kafka.username | quote }}
    password={{ .Values.secret.kafka.password | quote }};
